### ISSUE TITLE
We need a custom semiology lookup function

### ISSUE THREAD

**Issue by fepegar** [thenineteen/Semiology-Visualisation-Tool#124]
As discussed in today's meeting, we should have a way to tell the user that their custom term maps to an existing semiology. But then, is there a point in adding it to the GUI?

**Comment by thenineteen** [comment]
I envisaged a pop-up to notify you "Note: your custom semiology of `cephalic` exists currently under `Non-Specific Aura` - if you wish to only search for cephalic sensations, continue, otherwise try `Non-Specific Aura`"

or similar.

1. would need a way to tell the user has completed typing in their semiology, e.g. by pressing enter or clicking on a new `done` button (unless you want to get fancy and use predictive text as the user types)

2. then would search the semiology_dictionary and if found, find the key

**Comment by fepegar** [comment]
I see. Then we need a function f(custom_term) = category.

**Comment by thenineteen** [comment]
I think I've made this function in b1b186ec62f73b4e0181ca2e41917a0fe6603bb5

as per docstring:

```
User enters custom semiology.
    Top level function will use this to find a match within SemioDict:
        semiology_exists_already = custom_semiology_lookup(custom_semiology)
        if semiology_exists_already is None:
            pass
        else:
            pop-up window("Note this custom semiology may already exist within the category {}".format(k))
```

**Comment by fepegar** [comment]
It needs at least one test. I suggest you open a PR for it. At the moment the file raises a `SyntaxError`.

**Comment by thenineteen** [comment]
Ok will do

**Comment by thenineteen** [comment]
done

function corrected in 800f446f24add308b63c3b98b6a72244adec86bb
tests made in 4e90c7f45e91fddceaeedc92a694ed4f0d4d80bc

tests pass as expected. It is still conceuvable that certain terms may not be caught due to the regexes in the SemioBrain Dict (YAML) but this is unlikely and the best that can be done with the current version.

over to you

**Comment by thenineteen** [comment]
FYI this may help


Top level function will use this to find a match within SemioDict:
```

semiology_exists_already = custom_semiology_lookup(custom_semiology, found=[])
if not semiology_exists_already:
     pass
elif len(semiology_exists_already) == 1:
    pop-up window("Note this custom semiology may already exist within the category {}".format(semiology_exists_already[0]))
elif len(semiology_exists_already) > 1:
    pop-up window("Note this custom semiology term occurs in various ways within the following categories {}".format(str(semiology_exists_already)))

```

**Comment by fepegar** [comment]
What is the `SemioDict Taxonomy Replacement`?

**Comment by thenineteen** [comment]
aka semiology_dictionary.yaml

**Comment by thenineteen** [comment]
this is by far the coolest thing I've contributed to lol it's instant!
